# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0003_auto_20170314_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTest',
        ),
    ]
