# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rideshare', '0004_delete_usertest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedTrips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_email', models.CharField(max_length=100)),
                ('driver_departure', models.CharField(max_length=200)),
                ('driver_destination', models.CharField(max_length=200)),
                ('driver_timeofdeparture', models.CharField(max_length=10)),
                ('driver_days_monday', models.BooleanField(default=False)),
                ('driver_days_tuesday', models.BooleanField(default=False)),
                ('driver_days_wednesday', models.BooleanField(default=False)),
                ('driver_days_thursday', models.BooleanField(default=False)),
                ('driver_days_friday', models.BooleanField(default=False)),
                ('driver_days_saturday', models.BooleanField(default=False)),
                ('driver_days_sunday', models.BooleanField(default=False)),
            ],
        ),
    ]
