# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0005_plannedtrips'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedtrips',
            name='driver_days',
            field=models.CharField(default='xx', max_length=150),
            preserve_default=False,
        ),
    ]
