# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0006_plannedtrips_driver_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plannedtrips',
            old_name='driver_days_friday',
            new_name='friday',
        ),
        migrations.RenameField(
            model_name='plannedtrips',
            old_name='driver_days_monday',
            new_name='monday',
        ),
        migrations.RenameField(
            model_name='plannedtrips',
            old_name='driver_days_saturday',
            new_name='saturday',
        ),
        migrations.RenameField(
            model_name='plannedtrips',
            old_name='driver_days_sunday',
            new_name='sunday',
        ),
        migrations.RenameField(
            model_name='plannedtrips',
            old_name='driver_days_thursday',
            new_name='thursday',
        ),
        migrations.RenameField(
            model_name='plannedtrips',
            old_name='driver_days_tuesday',
            new_name='tuesday',
        ),
        migrations.RenameField(
            model_name='plannedtrips',
            old_name='driver_days_wednesday',
            new_name='wednesday',
        ),
    ]
