# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0007_auto_20170316_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedTrips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_email', models.CharField(max_length=100)),
                ('rider_departure', models.CharField(max_length=200)),
                ('rider_destination', models.CharField(max_length=200)),
                ('rider_timeofdeparture', models.CharField(max_length=10)),
                ('rider_days', models.CharField(max_length=150)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
            ],
        ),
    ]
