# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0009_auto_20170316_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedtrips',
            name='driver_days',
        ),
    ]
