# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 00:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rideshare', '0011_remove_proposedtrips_rider_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_trip', models.ManyToManyField(to='rideshare.PlannedTrips')),
                ('proposed_trip', models.ManyToManyField(to='rideshare.ProposedTrips')),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
