# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0012_rideprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideprofile',
            name='email',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
