# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0013_rideprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
