# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0014_riderjoin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedtrips',
            name='id',
        ),
        migrations.RemoveField(
            model_name='proposedtrips',
            name='id',
        ),
        migrations.AddField(
            model_name='plannedtrips',
            name='trip_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposedtrips',
            name='trip_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
