# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0015_auto_20170316_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedtrips',
            name='trip_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proposedtrips',
            name='trip_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
