# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0016_auto_20170316_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedtrips',
            name='trip_id',
        ),
        migrations.RemoveField(
            model_name='proposedtrips',
            name='trip_id',
        ),
        migrations.AddField(
            model_name='plannedtrips',
            name='id',
            field=models.AutoField(auto_created=True, default=2323, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposedtrips',
            name='id',
            field=models.AutoField(auto_created=True, default=2342, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
