# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0018_auto_20170316_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedtrips',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposedtrips',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plannedtrips',
            name='trip_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='proposedtrips',
            name='trip_id',
            field=models.PositiveIntegerField(),
        ),
    ]
