# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0020_auto_20170316_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedtrips',
            name='trip_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
