# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0022_auto_20170316_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderApproveTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve', models.BooleanField(default=False)),
                ('planned_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.PlannedTrips')),
            ],
        ),
        migrations.DeleteModel(
            name='RiderJoin',
        ),
        migrations.AddField(
            model_name='rideprofile',
            name='rider_destination',
            field=models.CharField(default='Dest', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rideprofile',
            name='rider_firstname',
            field=models.CharField(default='fname', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rideprofile',
            name='rider_lastname',
            field=models.CharField(default='lname', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rideprofile',
            name='rider_location',
            field=models.CharField(default='loc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rideprofile',
            name='rider_timeofdeparture',
            field=models.CharField(default='tofdep', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderapprovetrip',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.RideProfile'),
        ),
    ]
