# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 03:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rideshare', '0023_auto_20170318_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField(default=False)),
                ('driverod_email', models.CharField(max_length=100)),
                ('driverod_departure', models.CharField(max_length=200)),
                ('driverod_destination', models.CharField(max_length=200)),
                ('driverod_timeofdeparture', models.CharField(max_length=10)),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
