# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0025_rideractive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideractive',
            name='driverod_active_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideshare.DriverActive'),
        ),
    ]
