# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0027_auto_20170321_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideractive',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
    ]
