# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0028_rideractive_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rideractive',
            old_name='driverod_departure',
            new_name='riderod_departure',
        ),
        migrations.RenameField(
            model_name='rideractive',
            old_name='driverod_destination',
            new_name='riderod_destination',
        ),
    ]
