# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0030_auto_20170516_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedtrips',
            name='driver_departure_latitude',
            field=models.FloatField(default=989898, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannedtrips',
            name='driver_destination_latitude',
            field=models.FloatField(default=878787, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannedtrips',
            name='driver_timeofdeparture_minute',
            field=models.IntegerField(default=595959),
            preserve_default=False,
        ),
    ]
