# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0033_auto_20170516_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideractive',
            name='riderod_departure',
        ),
        migrations.RemoveField(
            model_name='rideractive',
            name='riderod_destination',
        ),
        migrations.AddField(
            model_name='rideractive',
            name='riderod_departure_lat',
            field=models.FloatField(default=147, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rideractive',
            name='riderod_departure_lon',
            field=models.FloatField(default=106, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rideractive',
            name='riderod_destination_lat',
            field=models.FloatField(default=147, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rideractive',
            name='riderod_destination_lon',
            field=models.FloatField(default=107, max_length=200),
            preserve_default=False,
        ),
    ]
