# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0036_auto_20170524_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedtrips',
            name='driver_departure_latitude',
            field=models.FloatField(max_length=500),
        ),
        migrations.AlterField(
            model_name='plannedtrips',
            name='driver_departure_longitude',
            field=models.FloatField(max_length=500),
        ),
        migrations.AlterField(
            model_name='plannedtrips',
            name='driver_destination_latitude',
            field=models.FloatField(max_length=500),
        ),
        migrations.AlterField(
            model_name='plannedtrips',
            name='driver_destination_longitude',
            field=models.FloatField(max_length=500),
        ),
    ]
