# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0037_auto_20170524_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideprofile',
            name='rider_destination',
        ),
        migrations.RemoveField(
            model_name='rideprofile',
            name='rider_location',
        ),
        migrations.AddField(
            model_name='rideprofile',
            name='rider_departure_lat',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rideprofile',
            name='rider_departure_lon',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rideprofile',
            name='rider_destination_lat',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rideprofile',
            name='rider_destination_lon',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
