# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0039_auto_20170524_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedtrips',
            name='driver_departure',
            field=models.CharField(default='dep_default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannedtrips',
            name='driver_destination',
            field=models.CharField(default='dri_dest_def', max_length=200),
            preserve_default=False,
        ),
    ]
