# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0041_auto_20170531_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideprofile',
            name='rider_departure',
            field=models.CharField(default='rider_dep_default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rideprofile',
            name='rider_destination',
            field=models.CharField(default='rider_dest_default', max_length=200),
            preserve_default=False,
        ),
    ]
