# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0042_auto_20170531_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideprofile',
            name='rider_timeofdeparture_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rideprofile',
            name='rider_timeofdeparture_minute',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
