# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0043_auto_20170607_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideractive',
            name='driverod_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
