# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0044_auto_20170612_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveractive',
            name='rejected_rider',
            field=models.ManyToManyField(related_name='RiderActiveRejected', to='rideshare.RiderActive'),
        ),
        migrations.AddField(
            model_name='rideractive',
            name='seen_driver',
            field=models.ManyToManyField(related_name='DriverActiveSeen', to='rideshare.DriverActive'),
        ),
    ]
