# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0045_auto_20170612_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveractive',
            name='rejected_rider',
            field=models.ManyToManyField(related_name='rejected_rider', to='rideshare.RiderActive'),
        ),
        migrations.AlterField(
            model_name='rideractive',
            name='seen_driver',
            field=models.ManyToManyField(related_name='seen_driver', to='rideshare.DriverActive'),
        ),
    ]
