# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0046_auto_20170612_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('point_count', models.IntegerField()),
                ('driver_approval', models.BooleanField(default=False)),
            ],
        ),
    ]
