# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0047_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='share_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
