# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0048_userprofile_share_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='World_Norcal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='destination_longitude',
            field=models.FloatField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='destinaton_latitude',
            field=models.FloatField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_latitude',
            field=models.FloatField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_longitude',
            field=models.FloatField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rideshare.World_Norcal'),
        ),
    ]
