# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0050_userprofile_driver_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rideshare.WorldInstance'),
        ),
        migrations.DeleteModel(
            name='World_Norcal',
        ),
    ]
