# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0051_auto_20170712_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='destinaton_latitude',
            new_name='destination_latitude',
        ),
    ]
