# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0052_auto_20170712_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_ride',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rideshare.ActiveRide'),
        ),
    ]
