# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0053_auto_20170713_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='active_ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rideshare.ActiveRide'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rideshare.WorldInstance'),
        ),
    ]
