# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0056_auto_20170719_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridehistory',
            name='rating',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
