# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0058_userprofile_car_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_total', models.IntegerField()),
                ('goal_current', models.IntegerField()),
                ('points_reward', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rideshare.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_total', models.IntegerField()),
                ('goal_current', models.IntegerField()),
                ('points_reward', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rideshare.UserProfile')),
            ],
        ),
    ]
