# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-29 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0059_monthlygoals_weeklygoals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='car_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
