# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0060_auto_20170729_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArityRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('tripid', models.CharField(max_length=200)),
                ('startlocation', models.CharField(max_length=100)),
                ('endlocation', models.CharField(max_length=100)),
                ('maximumspeed', models.FloatField(default=0, max_length=100)),
                ('speedingcount', models.IntegerField()),
                ('distancecovered', models.FloatField(default=0, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ridehistory',
            name='arity_ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rideshare.ArityRide'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='arity_ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rideshare.ArityRide'),
        ),
    ]
