# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0061_auto_20170917_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='arity_ride',
        ),
        migrations.AddField(
            model_name='arityride',
            name='arityride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rideshare.UserProfile'),
        ),
    ]
