# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0064_userprofile_safety_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='safety_score',
            new_name='tag_score',
        ),
    ]
